VietNguyen27/mallika-food-recipe

client/.gitignore
client/README.md
client/craco.config.ts
client/package-lock.json
client/package.json
client/public/index.html
client/src/App.tsx
client/src/index.js
client/tsconfig.json
client/tsconfig.path.json
nodemon.json
package-lock.json
package.json
server/index.ts
tsconfig.json

- api: to store api request functions (ex: file userApi  => register, login, update,...)
- assets: to store images, fonts family, fonts icon
- components: to store components like Button, Input,...
- config: to store constant variables (ex: HOST_API, PENDING, FULFILLED,...)
- features: to store redux slice (use global state management is redux toolkit)
- helpers: to store utility functions (ex: convertDate, capitalizeFirstLetter,...)
- hooks: to store custom hook (ex: useModal, useClickOutside,...)
- layout: to store layout (ex: Navbar, Header,...)
- pages: to store page (ex: HomePage, Profile,...)
- routes: to store all routes
- config: to store constant variables (ex: MAX_LENGTH, MIN_LENGTH,...)
- controllers: to store controllers (ex: user controllers)
- middlewares: to store …

Setup project, folder structure for both frontend and backend

---

server/controllers/authController.ts
server/controllers/userController.ts
server/index.ts
server/middlewares/authMiddleware.ts
server/models/userModel.ts
server/routes/authRoute.ts
server/routes/userRoute.ts
server/validations/authValidation.ts

register (POST): http://localhost:5000/api/auth/register (require: email, name, password, password_confirmation)
login (POST): http://localhost:5000/api/auth/login (require: email, password)
me (GET): http://localhost:5000/api/users/me (require: accessToken get after login)
user (GET): http://localhost:5000/api/users/:id (require: logged in successfully)
all (GET): http://localhost:5000/api/users/all (require: logged in successfully)

Change user route to auth route, add new route and auth middleware

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/pages/Auth/Login.tsx
client/src/pages/Auth/Register.tsx

Create register page

---

client/package-lock.json
client/package.json
client/src/api/auth.ts
client/src/api/axios.ts
client/src/components/Input/PasswordInput.tsx
client/src/components/Input/TextInput.tsx
client/src/config/constant.tsx
client/src/features/AuthSlice.tsx
client/src/helpers/helpers.ts
client/src/index.js
client/src/pages/Auth/Login.tsx
client/src/pages/Auth/Register.tsx
client/src/redux/reducers/index.ts
client/src/redux/store.ts
client/tsconfig.json
server/validations/authValidation.ts

Registration login function

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/Loading/Loading.tsx
client/src/config/contants.ts
client/src/helpers/helpers.ts
client/tailwind.config.js

Add lazy loading for components

---

client/src/App.tsx
client/src/api/auth.ts
client/src/api/axios.ts
client/src/components/Icon/Icon.tsx
client/src/components/Input/PasswordInput.tsx
client/src/components/Input/TextInput.tsx
client/src/components/Loading/Loading.tsx
client/src/config/constants.ts
client/src/config/contants.ts
client/src/features/AuthSlice.tsx
client/src/helpers/helpers.ts
client/src/index.js
client/src/pages/Auth/Login.tsx
client/src/pages/Auth/Register.tsx
client/src/pages/Home/Home.tsx
client/src/redux/reducers/index.ts
client/src/redux/store.ts
client/src/routes/PrivateRoute.tsx
client/src/routes/PubliceRoute.tsx
client/tailwind.config.js
client/tsconfig.path.json
server/validations/authValidation.ts

Add login feature, create loading spinner

---

server/config/validate.ts
server/controllers/authController.ts
server/controllers/recipeController.ts
server/index.ts
server/models/recipeModel.ts
server/models/userModel.ts
server/routes/recipeRoute.ts
server/validations/recipeValidation.ts

/:id (GET): http://localhost:5000/api/recipe/:id
/:id (PATCH): http://localhost:5000/api/recipe/:id
/:id (DELETE): http://localhost:5000/api/recipe/:id
/ (GET): http://localhost:5000/api/recipe
/ (POST): http://localhost:5000/api/recipe

Add validation and controller for recipe

---

client/src/components/Button/Button.tsx
client/src/components/Button/RoundedButton.tsx
client/src/components/Review/Review.tsx
client/src/components/Review/Reviews.tsx
client/src/components/Tabs/Tabs.tsx
client/src/helpers/helpers.ts
client/src/pages/Profile/Profile.tsx

Create review component

---

client/src/components/Category/CategoryItem.tsx
client/src/components/FeatureCard/FeatureCardItem.tsx
client/src/components/FeatureCard/FeatureCardList.tsx
client/src/pages/Home/Home.tsx
client/src/pages/Home/components/Categories.tsx
client/src/pages/Home/components/Cookbooks.tsx
client/src/pages/Home/components/FeaturedRecipes.tsx

Create featured component in homepage

---

client/src/pages/Home/Home.tsx
client/src/pages/Home/components/Categories.tsx
client/src/pages/Search/Search.tsx
client/src/pages/Search/components/LastSeen.tsx
client/src/pages/Search/components/RecentSearch.tsx

Create search component

---

client/src/App.tsx
client/src/api/auth.ts
client/src/api/axios.ts
client/src/components/Category/CategoryItem.tsx
client/src/components/FeatureCard/FeatureCardItem.tsx
client/src/components/FeatureCard/FeatureCardList.tsx
client/src/components/Input/PasswordInput.tsx
client/src/components/Input/TextInput.tsx
client/src/components/Tooltip/Tooltip.tsx
client/src/config/constants.ts
client/src/features/auth-slice.tsx
client/src/features/ui-slice.tsx
client/src/index.css
client/src/pages/Home/components/Categories.tsx
client/src/pages/Home/components/FeaturedRecipes.tsx
client/src/pages/Profile/Profile.tsx
client/src/pages/Profile/components/AccountDrawer.tsx
client/src/pages/Profile/components/EditProfileDrawer.tsx
server/controllers/recipeController.ts
server/controllers/userController.ts
server/models/userModel.ts
server/routes/userRoute.ts

Create edit profile drawer

---

client/src/components/Button/Button.tsx
client/src/components/Button/RoundedButton.tsx
client/src/components/FeatureCard/FeatureCardItem.tsx
client/src/components/Icon/Icon.tsx
client/src/components/Input/TextInput.tsx
client/src/components/Tabs/Tabs.tsx
client/src/components/Toast/ToastItem.tsx
client/src/components/Toast/ToastList.tsx
client/src/components/Tooltip/Tooltip.tsx
client/src/config/constants.ts
client/src/features/auth-slice.tsx
client/src/features/toast-slice.tsx
client/src/features/ui-slice.tsx
client/src/helpers/helpers.ts
client/src/layout/Navigation/Navigation.tsx
client/src/layout/Phone/Phone.tsx
client/src/pages/Auth/Login.tsx
client/src/pages/Auth/Register.tsx
client/src/pages/Home/Home.tsx
client/src/pages/Home/components/Categories.tsx
client/src/pages/Home/components/Cookbooks.tsx
client/src/pages/Landing/Landing.tsx
client/src/pages/Profile/Profile.tsx
client/src/pages/Profile/components/EditProfileDrawer.tsx
client/src/pages/Profile/components/NotificationDrawer.tsx
client/src/pages/Search/components/RecentSearch.tsx
client/src/pages/Splash/Splash.tsx
client/src/redux/reducers/index.ts
client/tailwind.config.js

Create toast slice, toast component, change key of enum

---

client/src/App.tsx
client/src/components/Drawer/Drawer.tsx
client/src/components/Input/SearchInput.tsx
client/src/components/Recipe/RecipeItem.tsx
client/src/components/Review/ReviewItem.tsx
client/src/components/Tabs/Tabs.tsx
client/src/index.css
client/src/layout/Phone/Phone.tsx
client/src/pages/Auth/Login.tsx
client/src/pages/Auth/Register.tsx
client/src/pages/DetailCookbook/DetailCookbook.tsx
client/src/pages/DetailCookbook/components/AllRecipe.tsx
client/src/pages/DetailCookbook/components/PopularRecipe.tsx
client/src/pages/Home/Home.tsx
client/src/pages/Home/components/Cookbooks.tsx
client/src/pages/Profile/components/AccountDrawer.tsx
client/src/pages/Profile/components/EditProfileDrawer.tsx
client/src/pages/Search/Search.tsx
client/src/pages/Search/components/LastSeen.tsx
client/src/pages/Search/components/RecentSearch.tsx
client/tailwind.config.js

create detail cookbook, add padding layout

---

client/src/components/Tabs/Tabs.tsx
client/src/pages/Home/components/FeaturedRecipes.tsx
client/src/pages/Profile/Profile.tsx

Create post tab in profile page, add scroll animation

---

client/src/components/Drawer/Drawer.tsx
client/src/components/Dropdown/Dropdown.tsx
client/src/components/Input/TextInput.tsx
client/src/components/Modal/Modal.tsx
client/src/components/RecipeDrawer/AddRecipeDrawer.tsx
client/src/components/RecipeDrawer/components/IngredientTab.tsx
client/src/components/RecipeDrawer/components/IntroTab.tsx
client/src/components/RecipeDrawer/components/RecipeWidget.tsx
client/src/components/RecipeDrawer/components/StepTab.tsx
client/src/components/Select/Select.tsx
client/src/components/Switch/Switch.tsx
client/src/components/Tabs/Tabs.tsx
client/src/hooks/useToggle.ts
client/tailwind.config.js

Create ingredients and steps tab in new recipe drawer

---

client/src/App.tsx
client/src/api/recipe.ts
client/src/components/FeatureCard/FeatureCardItem.tsx
client/src/components/FeatureCard/FeatureCardList.tsx
client/src/components/Input/PasswordInput.tsx
client/src/components/Input/TextInput.tsx
client/src/components/RecipeDrawer/components/IntroTab.tsx
client/src/components/RecipeDrawer/components/ModalAddWidget.tsx
client/src/components/Skeleton/Skeleton.tsx
client/src/config/constants.ts
client/src/features/loading-slice.ts
client/src/features/recipe-slice.ts
client/src/helpers/action-slice.ts
client/src/pages/Auth/Login.tsx
client/src/pages/Home/Home.tsx
client/src/pages/Home/components/FeaturedRecipes.tsx
client/src/pages/Profile/Profile.tsx
client/src/pages/Profile/components/AccountDrawer.tsx
client/src/redux/reducers/index.ts
server/controllers/recipe.controller.ts
server/index.ts
server/models/recipe.model.ts
server/routes/auth.route.ts
server/routes/recipe.route.ts
server/routes/user.route.ts
server/validations/recipe.validation.ts

Create controller for fetch personal recipes and others recipe, create skeleton for recipe card

---

client/src/api/auth.ts
client/src/api/recipe.ts
client/src/components/Card/Card.tsx
client/src/components/Loading/Loading.tsx
client/src/config/constants.ts
client/src/features/loading-slice.ts
client/src/features/recipe-slice.ts
client/src/pages/Home/components/CommunityDrawer.tsx
server/controllers/recipe.controller.ts
server/routes/recipe.route.ts

Add infinite scroll to recipe list in community drawer

---

client/src/App.tsx
client/src/components/Card/Card.tsx
client/src/components/RecipeDrawer/components/IntroTab.tsx
client/src/features/auth-slice.ts
client/src/pages/Splash/Splash.tsx
server/controllers/recipe.controller.ts
server/models/recipe.model.ts
server/models/user.model.ts

Handle logic first login to system, show splash page if user login the first time

---

client/src/api/liked.ts
client/src/api/recipe.ts
client/src/components/Card/Card.tsx
client/src/components/Recipe/Recipe.tsx
client/src/components/Skeleton/Skeleton.tsx
client/src/config/constants.ts
client/src/features/liked-slice.ts
client/src/features/loading-slice.ts
client/src/features/recipe-slice.ts
client/src/pages/DetailCookbook/components/AllRecipe.tsx
client/src/pages/Profile/components/LikedRecipeDrawer.tsx
client/src/pages/Search/components/LastSeen.tsx
client/src/redux/reducers/index.ts
server/controllers/auth.controller.ts
server/controllers/liked.controller.ts
server/controllers/recipe.controller.ts
server/controllers/user.controller.ts
server/index.ts
server/models/liked.model.ts
server/models/recipe.model.ts
server/models/review.model.ts
server/models/user.model.ts
server/routes/liked.route.ts
server/routes/recipe.route.ts

Create liked model, controller and routes. Handle logic add favorite recipe

---

client/src/components/RecipeDrawer/components/IngredientTab.tsx
client/src/components/RecipeDrawer/components/IntroTab.tsx
client/src/components/RecipeDrawer/components/ModalAddWidget.tsx
client/src/components/RecipeDrawer/components/RecipeWidget.tsx
client/src/components/RecipeDrawer/components/StepTab.tsx
client/src/components/Select/Select.tsx
client/src/components/Switch/Switch.tsx
client/src/features/recipe-slice.ts
server/controllers/recipe.controller.ts

Handle logic edit ingredients/steps item in new recipe drawer

---

client/src/App.tsx
client/src/api/recipe.ts
client/src/components/Card/Card.tsx
client/src/components/Skeleton/Skeleton.tsx
client/src/config/constants.ts
client/src/features/loading-slice.ts
client/src/features/recipe-slice.ts
client/src/layout/Content/Content.tsx
client/src/pages/DetailCookbook/DetailCookbook.tsx
client/src/pages/RecipeDetail/RecipeDetail.tsx

Create recipe detail page

---

client/src/App.tsx
client/src/common/AuthVerify.ts
client/src/components/Review/Review.tsx
client/src/components/ReviewDrawer/ReviewDrawer.tsx
client/src/components/Skeleton/Skeleton.tsx
client/src/config/constants.ts
client/src/config/review.ts
client/src/features/review-slice.ts
client/src/helpers/helpers.ts
client/src/pages/RecipeDetail/RecipeDetail.tsx
server/controllers/recipe.controller.ts
server/controllers/review.controller.ts

Add more options to edit, copy, delete reviews

---

client/src/api/review.ts
client/src/components/CollapseText/CollapseText.tsx
client/src/components/Review/Review.tsx
client/src/components/ReviewDrawer/ReviewDrawer.tsx
client/src/features/loading-slice.ts
client/src/features/review-slice.ts
client/src/pages/Profile/Profile.tsx
client/src/pages/RecipeDetail/RecipeDetail.tsx
package-lock.json
package.json
server/controllers/review.controller.ts
server/models/recipe.model.ts
server/models/review.model.ts
server/models/user.model.ts
server/routes/recipe.route.ts

Create collapse text component and handle logic load more reviews

---

client/src/components/Recipe/Recipe.tsx
client/src/features/lastseen-slice.ts
client/src/features/liked-slice.ts
client/src/features/recipe-slice.ts
client/src/index.js
client/src/pages/RecipeDetail/RecipeDetail.tsx
client/src/pages/Search/Search.tsx
client/src/pages/Search/components/LastSeen.tsx
client/src/pages/Search/components/RecentSearch.tsx
client/src/redux/reducers/index.ts

Create last seen recipes slice, save in session storage

---

client/src/App.tsx
client/src/api/auth.ts
client/src/api/recipe.ts
client/src/api/user.ts
client/src/components/Card/Card.tsx
client/src/components/Drawer/Drawer.tsx
client/src/components/RecipeDrawer/AddRecipeDrawer.tsx
client/src/components/RecipeDrawer/components/IntroTab.tsx
client/src/components/Review/Review.tsx
client/src/components/ReviewDrawer/ReviewDrawer.tsx
client/src/components/Tabs/Tabs.tsx
client/src/components/User/User.tsx
client/src/config/constants.ts
client/src/features/auth-slice.ts
client/src/features/loading-slice.ts
client/src/features/recipe-slice.ts
client/src/features/review-slice.ts
client/src/features/user-slice.ts
client/src/layout/Phone/Phone.tsx
client/src/pages/Home/Home.tsx
client/src/pages/Home/components/CommunityDrawer.tsx
client/src/pages/Profile/OtherProfile.tsx
client/src/pages/Profile/Profile.tsx
client/src/pages/RecipeDetail/RecipeDetail.tsx
client/src/pages/Search/Search.tsx
client/src/redux/reducers/index.ts
server/controllers/recipe.controller.ts
server/routes/recipe.route.ts

Change design of profile page and create another user profile page

---

client/src/api/follow.ts
client/src/components/Skeleton/Skeleton.tsx
client/src/components/Toast/Toast.tsx
client/src/components/UserCard/UserCard.tsx
client/src/features/auth-slice.ts
client/src/features/follow-slice.ts
client/src/features/lastseen-slice.ts
client/src/features/liked-slice.ts
client/src/features/loading-slice.ts
client/src/features/recipe-slice.ts
client/src/features/review-slice.ts
client/src/features/search-slice.ts
client/src/features/toast-slice.ts
client/src/features/ui-slice.ts
client/src/features/user-slice.ts
client/src/pages/Profile/OtherProfile.tsx
client/src/pages/Profile/Profile.tsx
client/src/pages/Profile/components/FollowersDrawer.tsx
client/src/pages/Profile/components/FollowingDrawer.tsx
client/src/pages/Search/components/SearchUser.tsx
client/src/redux/reducers/index.ts
server/controllers/review.controller.ts
server/controllers/user.controller.ts
server/routes/user.route.ts

Create followers following drawer, follow controller and slice, change base url of apis
